package=co.com.pragma
systemProp.version=3.25.0
reactive=true
lombok=true
metrics=true
language=java
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.integrity-check=true
systemProp.sonar.gradle.skipCompile=true
#JWT
security.jwt.key.private=44c85945bf275b34309169995aa43ccf737f9b2f332cdf5da777b664237f635a
security.jwt.user-generator=ADMIN123456
security.jwt.expiration=3600